# This is a basic workflow to help you get started with Actions

name: Production Deploy CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create-env-json
        uses: schdck/create-env-json@v2
        id: create-env
        with:
          file-name: 'assets/djangoSecret.json'
          djangoSecret: ${{ secrets.DJANGO_KEY }}
      - name: CloudFoundry push application with different directory
        uses: jhunt/cf-push@main
        with:
          appdir: "." # use the appdir option to select a specif folder where the cf app is stored
          api: ${{ secrets.PAAS_TA_URL }}
          org: ${{ secrets.PAAS_TA_ORG }}
          space: ${{ secrets.PAAS_TA_SPACE }}
          username: ${{ secrets.PAAS_TA_USER }}
          password: ${{ secrets.PAAS_TA_PASSWORD }}
          manifest: manifest.yml
          validate: true
